# Fulmen Application Identity
app:
  vendor: fulmenhq
  binary_name: limensafe
  env_prefix: LIMENSAFE_
  config_name: limensafe
  description: Detect Confidential Context Leakage in code, docs, and artifacts
  version: 0.0.5
metadata:
  repository_category: cli
  project_url: https://github.com/fulmenhq/limensafe
  license: Apache-2.0
