package catalog

import (
	"bufio"
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

// termListSeparator divides a protected term from its replacement on each
// mapping line: PROTECTED==>replacement.
const termListSeparator = "==>"

const (
	termListRegexPrefix       = "regex:"
	termListAllowlistLiteral  = "allowlist:literal:"
	termListAllowlistRegex    = "allowlist:regex:"
	termListRegexIDPrefix     = "e-rx-"
	termListAllowlistIDPrefix = "al-tl-"
)

// TermListOptions configures catalog generation from a flat term-list. The
// defaults mirror the validated "catalog-B" posture from the release-gate
// dogfoods: whole-word matching on (kills the substring-FP class), plus
// case-insensitive and slug variants.
type TermListOptions struct {
	CatalogID       string
	SchemaVersion   string // defaults to SupportedCatalogSchemaVersion
	DefaultClass    string // applied to entities without a class directive
	DefaultSeverity string // catalog-level default_severity
	// DisableWholeWord opts out of whole-word matching. Whole-word is the
	// catalog-B default (the zero value keeps it on); set this true only for
	// the explicit --no-whole-word opt-out.
	DisableWholeWord bool // variants.whole_word = !DisableWholeWord
}

// TermListError reports a problem in the term-list source. It is redaction-safe
// by construction: it names a line number and a structural reason only, never
// the protected term, replacement, or raw source line.
type TermListError struct {
	Line   int
	Reason string
}

func (e *TermListError) Error() string {
	return fmt.Sprintf("term-list line %d: %s", e.Line, e.Reason)
}

// Minimal output structs so generated YAML carries only populated fields.
// Marshaling the shared Catalog/Entity structs directly would emit empty
// enum/id fields (replacement_for, visibility_scope, severity_override) that
// fail JSON Schema validation; omitempty here keeps the output conformant.
type termListCatalogOut struct {
	Schema          string                 `yaml:"$schema"`
	CatalogID       string                 `yaml:"catalog_id"`
	SchemaVersion   string                 `yaml:"schema_version"`
	DefaultSeverity string                 `yaml:"default_severity,omitempty"`
	Entities        []termListEntityOut    `yaml:"entities"`
	Allowlist       []termListAllowlistOut `yaml:"allowlist,omitempty"`
}

type termListEntityOut struct {
	ID                    string               `yaml:"id"`
	Class                 string               `yaml:"class"`
	Aliases               []string             `yaml:"aliases,omitempty"`
	Variants              *termListVariantsOut `yaml:"variants,omitempty"`
	RegexPatterns         []string             `yaml:"regex_patterns,omitempty"`
	ReplacementSuggestion string               `yaml:"replacement_suggestion,omitempty"`
	SeverityOverride      string               `yaml:"severity_override,omitempty"`
}

type termListVariantsOut struct {
	CaseInsensitive bool `yaml:"case_insensitive"`
	Slug            bool `yaml:"slug"`
	WholeWord       bool `yaml:"whole_word"`
}

type termListAllowlistOut struct {
	ID       string                     `yaml:"id"`
	Kind     string                     `yaml:"kind"`
	Pattern  string                     `yaml:"pattern"`
	Variants *termListAllowlistVariants `yaml:"variants,omitempty"`
}

type termListAllowlistVariants struct {
	CaseInsensitive *bool `yaml:"case_insensitive,omitempty"`
	WholeWord       *bool `yaml:"whole_word,omitempty"`
}

type termListGroup struct {
	replacement string
	aliases     []string
	aliasSeen   map[string]struct{}
	// class/severity hold the group's explicitly-directed metadata; the empty
	// string means "no line in the group has specified it yet". classLine /
	// severityLine record where each was first set, for line-referenced
	// conflict diagnostics. The catalog-level default class is applied only
	// after all lines are read, and only when class is still unset.
	class        string
	classLine    int
	severity     string
	severityLine int
}

type termListRegexEntry struct {
	pattern  string
	line     int
	class    string
	severity string
}

type termListAllowlistEntry struct {
	kind            string
	pattern         string
	line            int
	caseInsensitive bool
	caseSet         bool
	wholeWord       bool
	wholeSet        bool
}

type termListDirective struct {
	class           string
	severity        string
	caseInsensitive bool
	caseSet         bool
	wholeWord       bool
	wholeSet        bool
}

// BuildCatalogFromTermList reads a PROTECTED==>replacement term-list, with
// optional structured regex:<pattern> and allowlist:<kind>:<pattern> lines, and
// returns conformant catalog YAML. Terms sharing a replacement group into one
// entity (replacement becomes replacement_suggestion). Generated entity and
// allowlist ids are stable, opaque, alias-free hashes. The generated bytes are
// re-loaded through LoadBytes so the returned output is guaranteed to pass
// schema + loader validation; output is deterministic (stable entity/alias
// ordering) so rebuilding the same input is byte-identical.
//
// Per-line overrides are accepted as a trailing directive:
//
//	PROTECTED==>replacement  # class=person severity=critical
//
// Errors are redaction-safe: they reference line numbers, never content.
func BuildCatalogFromTermList(r io.Reader, opts TermListOptions) ([]byte, error) {
	if strings.TrimSpace(opts.CatalogID) == "" {
		return nil, fmt.Errorf("term-list: catalog id is required")
	}
	schemaVersion := opts.SchemaVersion
	if schemaVersion == "" {
		schemaVersion = SupportedCatalogSchemaVersion
	}
	defaultClass := opts.DefaultClass
	if defaultClass == "" {
		defaultClass = "codename"
	}

	groups := map[string]*termListGroup{}
	var order []string // replacement keys in first-seen order (pre-sort)
	regexes := map[string]*termListRegexEntry{}
	var regexOrder []string
	allowlists := map[string]*termListAllowlistEntry{}
	var allowlistOrder []string

	addLiteralMapping := func(line string, lineNo int) error {
		protected, replacement, directive, perr := splitTermLine(line, lineNo)
		if perr != nil {
			return perr
		}
		d, derr := parseDirective(directive, lineNo)
		if derr != nil {
			return derr
		}
		if d.caseSet || d.wholeSet {
			return &TermListError{Line: lineNo, Reason: "directive key is not valid for literal mapping lines"}
		}

		g, ok := groups[replacement]
		if !ok {
			g = &termListGroup{
				replacement: replacement,
				aliasSeen:   map[string]struct{}{},
			}
			groups[replacement] = g
			order = append(order, replacement)
		}
		// Merge directed metadata into the group. An undirected line
		// contributes no class/severity opinion (it inherits the group's),
		// so metadata on the first line of a group is enough. A conflict is
		// two lines that both specify and disagree — reported by line number,
		// never by content.
		if d.class != "" {
			if g.class != "" && g.class != d.class {
				return &TermListError{Line: lineNo, Reason: fmt.Sprintf("class conflicts with the same replacement group's class set at line %d", g.classLine)}
			}
			g.class, g.classLine = d.class, lineNo
		}
		if d.severity != "" {
			if g.severity != "" && g.severity != d.severity {
				return &TermListError{Line: lineNo, Reason: fmt.Sprintf("severity conflicts with the same replacement group's severity set at line %d", g.severityLine)}
			}
			g.severity, g.severityLine = d.severity, lineNo
		}
		if _, dup := g.aliasSeen[protected]; !dup {
			g.aliasSeen[protected] = struct{}{}
			g.aliases = append(g.aliases, protected)
		}
		return nil
	}

	scanner := bufio.NewScanner(r)
	lineNo := 0
	for scanner.Scan() {
		lineNo++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.Contains(line, termListSeparator) {
			if err := addLiteralMapping(line, lineNo); err != nil {
				return nil, err
			}
			continue
		}
		if strings.HasPrefix(line, termListRegexPrefix) {
			pattern, directive := splitStructuredLine(line[len(termListRegexPrefix):])
			if strings.TrimSpace(pattern) == "" {
				return nil, &TermListError{Line: lineNo, Reason: "empty regex pattern"}
			}
			if _, err := regexp.Compile(pattern); err != nil {
				return nil, &TermListError{Line: lineNo, Reason: "regex pattern does not compile"}
			}
			d, derr := parseDirective(directive, lineNo)
			if derr != nil {
				return nil, derr
			}
			if d.caseSet || d.wholeSet {
				return nil, &TermListError{Line: lineNo, Reason: "directive key is not valid for regex detector lines"}
			}
			if prev, ok := regexes[pattern]; ok {
				if prev.class != d.class || prev.severity != d.severity {
					return nil, &TermListError{Line: lineNo, Reason: fmt.Sprintf("regex metadata conflicts with line %d", prev.line)}
				}
				continue
			}
			regexes[pattern] = &termListRegexEntry{
				pattern:  pattern,
				line:     lineNo,
				class:    d.class,
				severity: d.severity,
			}
			regexOrder = append(regexOrder, pattern)
			continue
		}
		if strings.HasPrefix(line, termListAllowlistLiteral) || strings.HasPrefix(line, termListAllowlistRegex) {
			kind := AllowlistKindLiteral
			rest := line[len(termListAllowlistLiteral):]
			if strings.HasPrefix(line, termListAllowlistRegex) {
				kind = AllowlistKindRegex
				rest = line[len(termListAllowlistRegex):]
			}
			pattern, directive := splitStructuredLine(rest)
			if strings.TrimSpace(pattern) == "" {
				return nil, &TermListError{Line: lineNo, Reason: "empty allowlist pattern"}
			}
			if kind == AllowlistKindRegex {
				if _, err := regexp.Compile(pattern); err != nil {
					return nil, &TermListError{Line: lineNo, Reason: "allowlist regex pattern does not compile"}
				}
			}
			d, derr := parseDirective(directive, lineNo)
			if derr != nil {
				return nil, derr
			}
			if d.class != "" || d.severity != "" {
				return nil, &TermListError{Line: lineNo, Reason: "directive key is not valid for allowlist lines"}
			}
			key := kind + "\x00" + pattern
			if prev, ok := allowlists[key]; ok {
				if prev.caseInsensitive != d.caseInsensitive || prev.caseSet != d.caseSet || prev.wholeWord != d.wholeWord || prev.wholeSet != d.wholeSet {
					return nil, &TermListError{Line: lineNo, Reason: fmt.Sprintf("allowlist metadata conflicts with line %d", prev.line)}
				}
				continue
			}
			allowlists[key] = &termListAllowlistEntry{
				kind:            kind,
				pattern:         pattern,
				line:            lineNo,
				caseInsensitive: d.caseInsensitive,
				caseSet:         d.caseSet,
				wholeWord:       d.wholeWord,
				wholeSet:        d.wholeSet,
			}
			allowlistOrder = append(allowlistOrder, key)
			continue
		}
		if err := addLiteralMapping(line, lineNo); err != nil {
			return nil, err
		}
	}
	if err := scanner.Err(); err != nil {
		// Value-free: this is exported API; a caller's custom io.Reader may
		// return an error carrying a path or protected content. Do not wrap it.
		return nil, fmt.Errorf("term-list: read input failed")
	}
	if len(order) == 0 && len(regexOrder) == 0 {
		return nil, fmt.Errorf("term-list: no mappings found (expected PROTECTED%sreplacement or regex:<pattern> lines)", termListSeparator)
	}

	entities := make([]termListEntityOut, 0, len(order)+len(regexOrder))
	for _, replacement := range order {
		g := groups[replacement]
		aliases := append([]string(nil), g.aliases...)
		sort.Strings(aliases)
		class := g.class
		if class == "" {
			class = defaultClass // no line in the group directed a class
		}
		entities = append(entities, termListEntityOut{
			ID:      termListEntityID(replacement),
			Class:   class,
			Aliases: aliases,
			Variants: &termListVariantsOut{
				CaseInsensitive: true,
				Slug:            true,
				WholeWord:       !opts.DisableWholeWord,
			},
			ReplacementSuggestion: replacement,
			SeverityOverride:      g.severity,
		})
	}
	for _, pattern := range regexOrder {
		r := regexes[pattern]
		class := r.class
		if class == "" {
			class = defaultClass
		}
		entities = append(entities, termListEntityOut{
			ID:               termListRegexEntityID(pattern),
			Class:            class,
			RegexPatterns:    []string{pattern},
			SeverityOverride: r.severity,
		})
	}
	// Deterministic, content-independent ordering by opaque id.
	sort.Slice(entities, func(i, j int) bool { return entities[i].ID < entities[j].ID })

	allowlistOut := make([]termListAllowlistOut, 0, len(allowlistOrder))
	for _, key := range allowlistOrder {
		a := allowlists[key]
		out := termListAllowlistOut{
			ID:      termListAllowlistID(a.kind, a.pattern),
			Kind:    a.kind,
			Pattern: a.pattern,
		}
		if a.caseSet || a.wholeSet {
			variants := &termListAllowlistVariants{}
			if a.caseSet {
				variants.CaseInsensitive = boolPtr(a.caseInsensitive)
			}
			if a.wholeSet {
				variants.WholeWord = boolPtr(a.wholeWord)
			}
			out.Variants = variants
		}
		allowlistOut = append(allowlistOut, out)
	}
	sort.Slice(allowlistOut, func(i, j int) bool { return allowlistOut[i].ID < allowlistOut[j].ID })

	out := termListCatalogOut{
		Schema:          catalogSchemaURI,
		CatalogID:       opts.CatalogID,
		SchemaVersion:   schemaVersion,
		DefaultSeverity: opts.DefaultSeverity,
		Entities:        entities,
		Allowlist:       allowlistOut,
	}
	data, err := yaml.Marshal(out)
	if err != nil {
		return nil, fmt.Errorf("term-list: encode catalog: %w", err)
	}
	// Round-trip through the loader so generated output is guaranteed to pass
	// schema + loader validation. LoadBytes diagnostics are redaction-safe.
	if _, err := LoadBytes(data); err != nil {
		return nil, fmt.Errorf("term-list: generated catalog failed validation: %w", err)
	}
	return data, nil
}

// splitTermLine parses one mapping line into its protected term, replacement,
// and optional trailing directive. Errors are line-numbered and value-free.
func splitTermLine(line string, lineNo int) (protected, replacement, directive string, err error) {
	idx := strings.Index(line, termListSeparator)
	if idx < 0 {
		return "", "", "", &TermListError{Line: lineNo, Reason: fmt.Sprintf("missing %q separator", termListSeparator)}
	}
	protected = strings.TrimSpace(line[:idx])
	rest := line[idx+len(termListSeparator):]
	// A directive begins at a " #" (hash preceded by whitespace), so a literal
	// '#' inside a replacement value is not misread as a comment.
	if d := strings.Index(rest, " #"); d >= 0 {
		directive = strings.TrimSpace(rest[d+2:])
		rest = rest[:d]
	}
	replacement = strings.TrimSpace(rest)
	if protected == "" {
		return "", "", "", &TermListError{Line: lineNo, Reason: "empty protected term"}
	}
	if replacement == "" {
		return "", "", "", &TermListError{Line: lineNo, Reason: "empty replacement value"}
	}
	return protected, replacement, directive, nil
}

// splitStructuredLine separates the structured line body from an optional
// trailing directive. A directive begins at a " #" (hash preceded by
// whitespace), matching splitTermLine so literal behavior stays byte-compatible.
func splitStructuredLine(rest string) (value, directive string) {
	if d := strings.Index(rest, " #"); d >= 0 {
		directive = strings.TrimSpace(rest[d+2:])
		rest = rest[:d]
	}
	return strings.TrimSpace(rest), directive
}

// parseDirective reads optional key=value tokens. Unknown keys are an error so
// typos surface; values are either value-free parsed here or validated
// downstream by the schema.
func parseDirective(directive string, lineNo int) (termListDirective, error) {
	var out termListDirective
	if directive == "" {
		return out, nil
	}
	for _, tok := range strings.Fields(directive) {
		k, v, ok := strings.Cut(tok, "=")
		if !ok || v == "" {
			return out, &TermListError{Line: lineNo, Reason: "malformed directive (expected key=value)"}
		}
		switch k {
		case "class":
			out.class = v
		case "severity":
			out.severity = v
		case "case_insensitive":
			b, err := parseDirectiveBool(v)
			if err != nil {
				return out, &TermListError{Line: lineNo, Reason: "malformed boolean directive value"}
			}
			out.caseInsensitive = b
			out.caseSet = true
		case "whole_word":
			b, err := parseDirectiveBool(v)
			if err != nil {
				return out, &TermListError{Line: lineNo, Reason: "malformed boolean directive value"}
			}
			out.wholeWord = b
			out.wholeSet = true
		default:
			// Value-free: the key is operator-controlled term-list content and
			// could itself be a protected token (ADR-0003 zero-leak applies to
			// malformed-input diagnostics too). Never echo it.
			return out, &TermListError{Line: lineNo, Reason: "unknown directive key"}
		}
	}
	return out, nil
}

func parseDirectiveBool(v string) (bool, error) {
	switch v {
	case "true":
		return true, nil
	case "false":
		return false, nil
	default:
		return false, fmt.Errorf("invalid boolean")
	}
}

func boolPtr(v bool) *bool {
	return &v
}

// termListEntityID derives a stable, opaque, alias-free entity id from the
// replacement group. It is hash-derived (never positional, never derived from
// protected text) so inserting a new group does not renumber others and the id
// can never carry protected vocabulary.
func termListEntityID(replacement string) string {
	sum := sha256.Sum256([]byte(replacement))
	return "e-tl-" + hex.EncodeToString(sum[:])[:12]
}

func termListRegexEntityID(pattern string) string {
	sum := sha256.Sum256([]byte(pattern))
	return termListRegexIDPrefix + hex.EncodeToString(sum[:])[:12]
}

func termListAllowlistID(kind, pattern string) string {
	sum := sha256.Sum256([]byte(kind + "\x00" + pattern))
	return termListAllowlistIDPrefix + hex.EncodeToString(sum[:])[:12]
}
